Update PythonSdkLiveTest.yml for Azure Pipelines

diff --git a/scripts/auto_release/PythonSdkLiveTest.yml b/scripts/auto_release/PythonSdkLiveTest.yml
--- a/scripts/auto_release/PythonSdkLiveTest.yml
+++ b/scripts/auto_release/PythonSdkLiveTest.yml
@@ -24,10 +24,10 @@ jobs:
         architecture: 'x64'
     - bash: |
         # verify $ISSUE_LINK and $BASE_BRANCH is not null
-        if [ -z "$(BASE_BRANCH)" -o -z "$(ISSUE_LINK)" ]; then
-          echo "ISSUE_LINK or BASE_BRANCH do not exist, pipeline fail!!!"
-          exit 1
-        fi
+        # if [ -z "$(BASE_BRANCH)" -o -z "$(ISSUE_LINK)" ]; then
+        #   echo "ISSUE_LINK or BASE_BRANCH do not exist, pipeline fail!!!"
+        #   exit 1
+        # fi
 
         script_path=$(pwd)/scripts/auto_release
         cd ..
